name: Dev Bug Report
description: Report an bug found during Early Development of Banner
labels: [ report ]
body:
- type: input
  id: commit
  attributes:
    label: Commit ID
    description: "What Fork, Branch, and commit is your build using?"
    placeholder: "e.g. <fork-user>/<branch>: <commitID>)"
  validations:
    required: true
- type: input
  id: logfile
  attributes:
    label: Log with Error
    description: "The link to your debug.log (uploaded to mclo.gs or haste.mohistmc.com)"
  validations:
    required: true
- type: textarea
  id: body
  attributes:
    label: Description of Error
    description: | 
      Describe the error and steps to recreate it within the development environment
      Note we only accept logs obtained from using `./gradlew runServer` inside the repo
      as this will give us more information about what went wrong so that we can fix it
